// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9TVcrocS5f49nsJcqhNvor2CHnzWYFVk',
    appId: '1:80531112537:android:f7e4f23bd157d759ab6748',
    messagingSenderId: '80531112537',
    projectId: 'e-shop-32eaa',
    databaseURL: 'https://e-shop-32eaa-default-rtdb.firebaseio.com',
    storageBucket: 'e-shop-32eaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvx7TMNQ0kNt4Afd2pKF5Xbm823FVZdRA',
    appId: '1:80531112537:ios:7d4f82734839b371ab6748',
    messagingSenderId: '80531112537',
    projectId: 'e-shop-32eaa',
    databaseURL: 'https://e-shop-32eaa-default-rtdb.firebaseio.com',
    storageBucket: 'e-shop-32eaa.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

}